/*
Kubernetes Operations APIs

Testing SecretProviderClassDetailApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rafaysdkgov3

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_rafaysdkgov3_SecretProviderClassDetailApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SecretProviderClassDetailApiService ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclassesNameArtifactsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.SecretProviderClassDetailApi.ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclassesNameArtifactsGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretProviderClassDetailApiService ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclassesNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.SecretProviderClassDetailApi.ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclassesNameGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretProviderClassDetailApiService ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclasssNameArtifactsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.SecretProviderClassDetailApi.ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclasssNameArtifactsGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretProviderClassDetailApiService ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclasssNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.SecretProviderClassDetailApi.ApisIntegrationsK8smgmtIoV3ProjectsProjectSecretproviderclasssNameGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
