/*
Kubernetes Operations APIs

Testing CredentialsDetailApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rafaysdkgov3

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_rafaysdkgov3_CredentialsDetailApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CredentialsDetailApiService ApisInfraK8smgmtIoV3ProjectsProjectCredentialsNameArtifactsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.CredentialsDetailApi.ApisInfraK8smgmtIoV3ProjectsProjectCredentialsNameArtifactsGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CredentialsDetailApiService ApisInfraK8smgmtIoV3ProjectsProjectCredentialsNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.CredentialsDetailApi.ApisInfraK8smgmtIoV3ProjectsProjectCredentialsNameGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CredentialsDetailApiService ApisInfraK8smgmtIoV3ProjectsProjectCredentialssNameArtifactsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.CredentialsDetailApi.ApisInfraK8smgmtIoV3ProjectsProjectCredentialssNameArtifactsGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CredentialsDetailApiService ApisInfraK8smgmtIoV3ProjectsProjectCredentialssNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.CredentialsDetailApi.ApisInfraK8smgmtIoV3ProjectsProjectCredentialssNameGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
