/*
Kubernetes Operations APIs

Testing ClusterNetworkPolicyRuleDetailApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rafaysdkgov3

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_rafaysdkgov3_ClusterNetworkPolicyRuleDetailApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ClusterNetworkPolicyRuleDetailApiService ApisSecurityK8smgmtIoV3ProjectsProjectClusternetworkpolicyrulesNameArtifactsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.ClusterNetworkPolicyRuleDetailApi.ApisSecurityK8smgmtIoV3ProjectsProjectClusternetworkpolicyrulesNameArtifactsGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ClusterNetworkPolicyRuleDetailApiService ApisSecurityK8smgmtIoV3ProjectsProjectClusternetworkpolicyrulesNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var project string
		var name string

		resp, httpRes, err := apiClient.ClusterNetworkPolicyRuleDetailApi.ApisSecurityK8smgmtIoV3ProjectsProjectClusternetworkpolicyrulesNameGet(context.Background(), project, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
