/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the ClusterMeshPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterMeshPolicy{}

// ClusterMeshPolicy Cluster policy definition
type ClusterMeshPolicy struct {
	// API Version of the cluster policy resource
	ApiVersion string `json:"apiVersion"`
	// Kind of the cluster policy resource
	Kind string `json:"kind"`
	Metadata Metadata `json:"metadata"`
	Spec ClusterMeshPolicySpec `json:"spec"`
}

// NewClusterMeshPolicy instantiates a new ClusterMeshPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterMeshPolicy(apiVersion string, kind string, metadata Metadata, spec ClusterMeshPolicySpec) *ClusterMeshPolicy {
	this := ClusterMeshPolicy{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewClusterMeshPolicyWithDefaults instantiates a new ClusterMeshPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterMeshPolicyWithDefaults() *ClusterMeshPolicy {
	this := ClusterMeshPolicy{}
	var apiVersion string = "servicemesh.k8smgmt.io/v3"
	this.ApiVersion = apiVersion
	var kind string = "ClusterMeshPolicy"
	this.Kind = kind
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *ClusterMeshPolicy) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *ClusterMeshPolicy) GetApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *ClusterMeshPolicy) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *ClusterMeshPolicy) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ClusterMeshPolicy) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ClusterMeshPolicy) SetKind(v string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *ClusterMeshPolicy) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *ClusterMeshPolicy) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *ClusterMeshPolicy) SetMetadata(v Metadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *ClusterMeshPolicy) GetSpec() ClusterMeshPolicySpec {
	if o == nil {
		var ret ClusterMeshPolicySpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *ClusterMeshPolicy) GetSpecOk() (*ClusterMeshPolicySpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *ClusterMeshPolicy) SetSpec(v ClusterMeshPolicySpec) {
	o.Spec = v
}

func (o ClusterMeshPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterMeshPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiVersion"] = o.ApiVersion
	toSerialize["kind"] = o.Kind
	toSerialize["metadata"] = o.Metadata
	toSerialize["spec"] = o.Spec
	return toSerialize, nil
}

type NullableClusterMeshPolicy struct {
	value *ClusterMeshPolicy
	isSet bool
}

func (v NullableClusterMeshPolicy) Get() *ClusterMeshPolicy {
	return v.value
}

func (v *NullableClusterMeshPolicy) Set(val *ClusterMeshPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterMeshPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterMeshPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterMeshPolicy(val *ClusterMeshPolicy) *NullableClusterMeshPolicy {
	return &NullableClusterMeshPolicy{value: val, isSet: true}
}

func (v NullableClusterMeshPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterMeshPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


