/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the UploadedYAMLArtifact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadedYAMLArtifact{}

// UploadedYAMLArtifact represents a list of YAML files
type UploadedYAMLArtifact struct {
	// list of YAML files represented by their relative path
	Paths []File `json:"paths"`
}

// NewUploadedYAMLArtifact instantiates a new UploadedYAMLArtifact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadedYAMLArtifact(paths []File) *UploadedYAMLArtifact {
	this := UploadedYAMLArtifact{}
	this.Paths = paths
	return &this
}

// NewUploadedYAMLArtifactWithDefaults instantiates a new UploadedYAMLArtifact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadedYAMLArtifactWithDefaults() *UploadedYAMLArtifact {
	this := UploadedYAMLArtifact{}
	return &this
}

// GetPaths returns the Paths field value
func (o *UploadedYAMLArtifact) GetPaths() []File {
	if o == nil {
		var ret []File
		return ret
	}

	return o.Paths
}

// GetPathsOk returns a tuple with the Paths field value
// and a boolean to check if the value has been set.
func (o *UploadedYAMLArtifact) GetPathsOk() ([]File, bool) {
	if o == nil {
		return nil, false
	}
	return o.Paths, true
}

// SetPaths sets field value
func (o *UploadedYAMLArtifact) SetPaths(v []File) {
	o.Paths = v
}

func (o UploadedYAMLArtifact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadedYAMLArtifact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["paths"] = o.Paths
	return toSerialize, nil
}

type NullableUploadedYAMLArtifact struct {
	value *UploadedYAMLArtifact
	isSet bool
}

func (v NullableUploadedYAMLArtifact) Get() *UploadedYAMLArtifact {
	return v.value
}

func (v *NullableUploadedYAMLArtifact) Set(val *UploadedYAMLArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadedYAMLArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadedYAMLArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadedYAMLArtifact(val *UploadedYAMLArtifact) *NullableUploadedYAMLArtifact {
	return &NullableUploadedYAMLArtifact{value: val, isSet: true}
}

func (v NullableUploadedYAMLArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadedYAMLArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


