/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the RepoNamespace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepoNamespace{}

// RepoNamespace namespace from git repository
type RepoNamespace struct {
	Path *File `json:"path,omitempty"`
	// name of the git repository
	Repository *string `json:"repository,omitempty"`
	// branch or tag in the git repository
	Revision *string `json:"revision,omitempty"`
}

// NewRepoNamespace instantiates a new RepoNamespace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepoNamespace() *RepoNamespace {
	this := RepoNamespace{}
	return &this
}

// NewRepoNamespaceWithDefaults instantiates a new RepoNamespace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepoNamespaceWithDefaults() *RepoNamespace {
	this := RepoNamespace{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *RepoNamespace) GetPath() File {
	if o == nil || isNil(o.Path) {
		var ret File
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepoNamespace) GetPathOk() (*File, bool) {
	if o == nil || isNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *RepoNamespace) HasPath() bool {
	if o != nil && !isNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given File and assigns it to the Path field.
func (o *RepoNamespace) SetPath(v File) {
	o.Path = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *RepoNamespace) GetRepository() string {
	if o == nil || isNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepoNamespace) GetRepositoryOk() (*string, bool) {
	if o == nil || isNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *RepoNamespace) HasRepository() bool {
	if o != nil && !isNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *RepoNamespace) SetRepository(v string) {
	o.Repository = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *RepoNamespace) GetRevision() string {
	if o == nil || isNil(o.Revision) {
		var ret string
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepoNamespace) GetRevisionOk() (*string, bool) {
	if o == nil || isNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *RepoNamespace) HasRevision() bool {
	if o != nil && !isNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given string and assigns it to the Revision field.
func (o *RepoNamespace) SetRevision(v string) {
	o.Revision = &v
}

func (o RepoNamespace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepoNamespace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !isNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !isNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	return toSerialize, nil
}

type NullableRepoNamespace struct {
	value *RepoNamespace
	isSet bool
}

func (v NullableRepoNamespace) Get() *RepoNamespace {
	return v.value
}

func (v *NullableRepoNamespace) Set(val *RepoNamespace) {
	v.value = val
	v.isSet = true
}

func (v NullableRepoNamespace) IsSet() bool {
	return v.isSet
}

func (v *NullableRepoNamespace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepoNamespace(val *RepoNamespace) *NullableRepoNamespace {
	return &NullableRepoNamespace{value: val, isSet: true}
}

func (v NullableRepoNamespace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepoNamespace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


