/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the MeshProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeshProfile{}

// MeshProfile Profile definition
type MeshProfile struct {
	// API Version of the profile resource
	ApiVersion string `json:"apiVersion"`
	// Kind of the profile resource
	Kind string `json:"kind"`
	Metadata Metadata `json:"metadata"`
	Spec MeshProfileSpec `json:"spec"`
}

// NewMeshProfile instantiates a new MeshProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeshProfile(apiVersion string, kind string, metadata Metadata, spec MeshProfileSpec) *MeshProfile {
	this := MeshProfile{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewMeshProfileWithDefaults instantiates a new MeshProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeshProfileWithDefaults() *MeshProfile {
	this := MeshProfile{}
	var apiVersion string = "servicemesh.k8smgmt.io/v3"
	this.ApiVersion = apiVersion
	var kind string = "MeshProfile"
	this.Kind = kind
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *MeshProfile) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *MeshProfile) GetApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *MeshProfile) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *MeshProfile) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *MeshProfile) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *MeshProfile) SetKind(v string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *MeshProfile) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *MeshProfile) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *MeshProfile) SetMetadata(v Metadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *MeshProfile) GetSpec() MeshProfileSpec {
	if o == nil {
		var ret MeshProfileSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *MeshProfile) GetSpecOk() (*MeshProfileSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *MeshProfile) SetSpec(v MeshProfileSpec) {
	o.Spec = v
}

func (o MeshProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeshProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiVersion"] = o.ApiVersion
	toSerialize["kind"] = o.Kind
	toSerialize["metadata"] = o.Metadata
	toSerialize["spec"] = o.Spec
	return toSerialize, nil
}

type NullableMeshProfile struct {
	value *MeshProfile
	isSet bool
}

func (v NullableMeshProfile) Get() *MeshProfile {
	return v.value
}

func (v *NullableMeshProfile) Set(val *MeshProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableMeshProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableMeshProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeshProfile(val *MeshProfile) *NullableMeshProfile {
	return &NullableMeshProfile{value: val, isSet: true}
}

func (v NullableMeshProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeshProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


