/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the MinioCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MinioCredentials{}

// MinioCredentials Minio Credentials definition
type MinioCredentials struct {
	AccessId string `json:"accessId"`
	SecretKey string `json:"secretKey"`
}

// NewMinioCredentials instantiates a new MinioCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMinioCredentials(accessId string, secretKey string) *MinioCredentials {
	this := MinioCredentials{}
	this.AccessId = accessId
	this.SecretKey = secretKey
	return &this
}

// NewMinioCredentialsWithDefaults instantiates a new MinioCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMinioCredentialsWithDefaults() *MinioCredentials {
	this := MinioCredentials{}
	return &this
}

// GetAccessId returns the AccessId field value
func (o *MinioCredentials) GetAccessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessId
}

// GetAccessIdOk returns a tuple with the AccessId field value
// and a boolean to check if the value has been set.
func (o *MinioCredentials) GetAccessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessId, true
}

// SetAccessId sets field value
func (o *MinioCredentials) SetAccessId(v string) {
	o.AccessId = v
}

// GetSecretKey returns the SecretKey field value
func (o *MinioCredentials) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *MinioCredentials) GetSecretKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *MinioCredentials) SetSecretKey(v string) {
	o.SecretKey = v
}

func (o MinioCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MinioCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessId"] = o.AccessId
	toSerialize["secretKey"] = o.SecretKey
	return toSerialize, nil
}

type NullableMinioCredentials struct {
	value *MinioCredentials
	isSet bool
}

func (v NullableMinioCredentials) Get() *MinioCredentials {
	return v.value
}

func (v *NullableMinioCredentials) Set(val *MinioCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableMinioCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableMinioCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinioCredentials(val *MinioCredentials) *NullableMinioCredentials {
	return &NullableMinioCredentials{value: val, isSet: true}
}

func (v NullableMinioCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinioCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


