/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the InlineOverrideTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineOverrideTemplate{}

// InlineOverrideTemplate inline override template definition
type InlineOverrideTemplate struct {
	// inline override template
	Inline string `json:"inline"`
}

// NewInlineOverrideTemplate instantiates a new InlineOverrideTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineOverrideTemplate(inline string) *InlineOverrideTemplate {
	this := InlineOverrideTemplate{}
	this.Inline = inline
	return &this
}

// NewInlineOverrideTemplateWithDefaults instantiates a new InlineOverrideTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineOverrideTemplateWithDefaults() *InlineOverrideTemplate {
	this := InlineOverrideTemplate{}
	return &this
}

// GetInline returns the Inline field value
func (o *InlineOverrideTemplate) GetInline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Inline
}

// GetInlineOk returns a tuple with the Inline field value
// and a boolean to check if the value has been set.
func (o *InlineOverrideTemplate) GetInlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inline, true
}

// SetInline sets field value
func (o *InlineOverrideTemplate) SetInline(v string) {
	o.Inline = v
}

func (o InlineOverrideTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineOverrideTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inline"] = o.Inline
	return toSerialize, nil
}

type NullableInlineOverrideTemplate struct {
	value *InlineOverrideTemplate
	isSet bool
}

func (v NullableInlineOverrideTemplate) Get() *InlineOverrideTemplate {
	return v.value
}

func (v *NullableInlineOverrideTemplate) Set(val *InlineOverrideTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineOverrideTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineOverrideTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineOverrideTemplate(val *InlineOverrideTemplate) *NullableInlineOverrideTemplate {
	return &NullableInlineOverrideTemplate{value: val, isSet: true}
}

func (v NullableInlineOverrideTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineOverrideTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


