/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the Podidentityprofile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Podidentityprofile{}

// Podidentityprofile struct for Podidentityprofile
type Podidentityprofile struct {
	// Running in Kubenet is disabled by default due to the security related nature of AAD Pod Identity and the risks of IP spoofing. See https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#using-kubenet-network-plugin-with-azure-active-directory-pod-managed-identities for more information.
	AllowNetworkPluginKubenet *bool `json:"allowNetworkPluginKubenet,omitempty"`
	// Whether the pod identity addon is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// The pod identities to use in the cluster.
	UserAssignedIdentities []Userassignedidentities `json:"userAssignedIdentities,omitempty"`
	// The pod identity exceptions to allow.
	UserAssignedIdentityExceptions []Userassignedidentityexceptions `json:"userAssignedIdentityExceptions,omitempty"`
}

// NewPodidentityprofile instantiates a new Podidentityprofile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPodidentityprofile() *Podidentityprofile {
	this := Podidentityprofile{}
	return &this
}

// NewPodidentityprofileWithDefaults instantiates a new Podidentityprofile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPodidentityprofileWithDefaults() *Podidentityprofile {
	this := Podidentityprofile{}
	return &this
}

// GetAllowNetworkPluginKubenet returns the AllowNetworkPluginKubenet field value if set, zero value otherwise.
func (o *Podidentityprofile) GetAllowNetworkPluginKubenet() bool {
	if o == nil || isNil(o.AllowNetworkPluginKubenet) {
		var ret bool
		return ret
	}
	return *o.AllowNetworkPluginKubenet
}

// GetAllowNetworkPluginKubenetOk returns a tuple with the AllowNetworkPluginKubenet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Podidentityprofile) GetAllowNetworkPluginKubenetOk() (*bool, bool) {
	if o == nil || isNil(o.AllowNetworkPluginKubenet) {
		return nil, false
	}
	return o.AllowNetworkPluginKubenet, true
}

// HasAllowNetworkPluginKubenet returns a boolean if a field has been set.
func (o *Podidentityprofile) HasAllowNetworkPluginKubenet() bool {
	if o != nil && !isNil(o.AllowNetworkPluginKubenet) {
		return true
	}

	return false
}

// SetAllowNetworkPluginKubenet gets a reference to the given bool and assigns it to the AllowNetworkPluginKubenet field.
func (o *Podidentityprofile) SetAllowNetworkPluginKubenet(v bool) {
	o.AllowNetworkPluginKubenet = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *Podidentityprofile) GetEnabled() bool {
	if o == nil || isNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Podidentityprofile) GetEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *Podidentityprofile) HasEnabled() bool {
	if o != nil && !isNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *Podidentityprofile) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetUserAssignedIdentities returns the UserAssignedIdentities field value if set, zero value otherwise.
func (o *Podidentityprofile) GetUserAssignedIdentities() []Userassignedidentities {
	if o == nil || isNil(o.UserAssignedIdentities) {
		var ret []Userassignedidentities
		return ret
	}
	return o.UserAssignedIdentities
}

// GetUserAssignedIdentitiesOk returns a tuple with the UserAssignedIdentities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Podidentityprofile) GetUserAssignedIdentitiesOk() ([]Userassignedidentities, bool) {
	if o == nil || isNil(o.UserAssignedIdentities) {
		return nil, false
	}
	return o.UserAssignedIdentities, true
}

// HasUserAssignedIdentities returns a boolean if a field has been set.
func (o *Podidentityprofile) HasUserAssignedIdentities() bool {
	if o != nil && !isNil(o.UserAssignedIdentities) {
		return true
	}

	return false
}

// SetUserAssignedIdentities gets a reference to the given []Userassignedidentities and assigns it to the UserAssignedIdentities field.
func (o *Podidentityprofile) SetUserAssignedIdentities(v []Userassignedidentities) {
	o.UserAssignedIdentities = v
}

// GetUserAssignedIdentityExceptions returns the UserAssignedIdentityExceptions field value if set, zero value otherwise.
func (o *Podidentityprofile) GetUserAssignedIdentityExceptions() []Userassignedidentityexceptions {
	if o == nil || isNil(o.UserAssignedIdentityExceptions) {
		var ret []Userassignedidentityexceptions
		return ret
	}
	return o.UserAssignedIdentityExceptions
}

// GetUserAssignedIdentityExceptionsOk returns a tuple with the UserAssignedIdentityExceptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Podidentityprofile) GetUserAssignedIdentityExceptionsOk() ([]Userassignedidentityexceptions, bool) {
	if o == nil || isNil(o.UserAssignedIdentityExceptions) {
		return nil, false
	}
	return o.UserAssignedIdentityExceptions, true
}

// HasUserAssignedIdentityExceptions returns a boolean if a field has been set.
func (o *Podidentityprofile) HasUserAssignedIdentityExceptions() bool {
	if o != nil && !isNil(o.UserAssignedIdentityExceptions) {
		return true
	}

	return false
}

// SetUserAssignedIdentityExceptions gets a reference to the given []Userassignedidentityexceptions and assigns it to the UserAssignedIdentityExceptions field.
func (o *Podidentityprofile) SetUserAssignedIdentityExceptions(v []Userassignedidentityexceptions) {
	o.UserAssignedIdentityExceptions = v
}

func (o Podidentityprofile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Podidentityprofile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AllowNetworkPluginKubenet) {
		toSerialize["allowNetworkPluginKubenet"] = o.AllowNetworkPluginKubenet
	}
	if !isNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !isNil(o.UserAssignedIdentities) {
		toSerialize["userAssignedIdentities"] = o.UserAssignedIdentities
	}
	if !isNil(o.UserAssignedIdentityExceptions) {
		toSerialize["userAssignedIdentityExceptions"] = o.UserAssignedIdentityExceptions
	}
	return toSerialize, nil
}

type NullablePodidentityprofile struct {
	value *Podidentityprofile
	isSet bool
}

func (v NullablePodidentityprofile) Get() *Podidentityprofile {
	return v.value
}

func (v *NullablePodidentityprofile) Set(val *Podidentityprofile) {
	v.value = val
	v.isSet = true
}

func (v NullablePodidentityprofile) IsSet() bool {
	return v.isSet
}

func (v *NullablePodidentityprofile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePodidentityprofile(val *Podidentityprofile) *NullablePodidentityprofile {
	return &NullablePodidentityprofile{value: val, isSet: true}
}

func (v NullablePodidentityprofile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePodidentityprofile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


