/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the NamespaceNetworkPolicyRuleSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NamespaceNetworkPolicyRuleSpec{}

// NamespaceNetworkPolicyRuleSpec namespace network policy rule  specification
type NamespaceNetworkPolicyRuleSpec struct {
	Artifact *ArtifactSpec `json:"artifact,omitempty"`
	Sharing *SharingSpec `json:"sharing,omitempty"`
	// version of the namespace policy rule
	Version *string `json:"version,omitempty"`
}

// NewNamespaceNetworkPolicyRuleSpec instantiates a new NamespaceNetworkPolicyRuleSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceNetworkPolicyRuleSpec() *NamespaceNetworkPolicyRuleSpec {
	this := NamespaceNetworkPolicyRuleSpec{}
	return &this
}

// NewNamespaceNetworkPolicyRuleSpecWithDefaults instantiates a new NamespaceNetworkPolicyRuleSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceNetworkPolicyRuleSpecWithDefaults() *NamespaceNetworkPolicyRuleSpec {
	this := NamespaceNetworkPolicyRuleSpec{}
	return &this
}

// GetArtifact returns the Artifact field value if set, zero value otherwise.
func (o *NamespaceNetworkPolicyRuleSpec) GetArtifact() ArtifactSpec {
	if o == nil || isNil(o.Artifact) {
		var ret ArtifactSpec
		return ret
	}
	return *o.Artifact
}

// GetArtifactOk returns a tuple with the Artifact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceNetworkPolicyRuleSpec) GetArtifactOk() (*ArtifactSpec, bool) {
	if o == nil || isNil(o.Artifact) {
		return nil, false
	}
	return o.Artifact, true
}

// HasArtifact returns a boolean if a field has been set.
func (o *NamespaceNetworkPolicyRuleSpec) HasArtifact() bool {
	if o != nil && !isNil(o.Artifact) {
		return true
	}

	return false
}

// SetArtifact gets a reference to the given ArtifactSpec and assigns it to the Artifact field.
func (o *NamespaceNetworkPolicyRuleSpec) SetArtifact(v ArtifactSpec) {
	o.Artifact = &v
}

// GetSharing returns the Sharing field value if set, zero value otherwise.
func (o *NamespaceNetworkPolicyRuleSpec) GetSharing() SharingSpec {
	if o == nil || isNil(o.Sharing) {
		var ret SharingSpec
		return ret
	}
	return *o.Sharing
}

// GetSharingOk returns a tuple with the Sharing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceNetworkPolicyRuleSpec) GetSharingOk() (*SharingSpec, bool) {
	if o == nil || isNil(o.Sharing) {
		return nil, false
	}
	return o.Sharing, true
}

// HasSharing returns a boolean if a field has been set.
func (o *NamespaceNetworkPolicyRuleSpec) HasSharing() bool {
	if o != nil && !isNil(o.Sharing) {
		return true
	}

	return false
}

// SetSharing gets a reference to the given SharingSpec and assigns it to the Sharing field.
func (o *NamespaceNetworkPolicyRuleSpec) SetSharing(v SharingSpec) {
	o.Sharing = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *NamespaceNetworkPolicyRuleSpec) GetVersion() string {
	if o == nil || isNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamespaceNetworkPolicyRuleSpec) GetVersionOk() (*string, bool) {
	if o == nil || isNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *NamespaceNetworkPolicyRuleSpec) HasVersion() bool {
	if o != nil && !isNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *NamespaceNetworkPolicyRuleSpec) SetVersion(v string) {
	o.Version = &v
}

func (o NamespaceNetworkPolicyRuleSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NamespaceNetworkPolicyRuleSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Artifact) {
		toSerialize["artifact"] = o.Artifact
	}
	if !isNil(o.Sharing) {
		toSerialize["sharing"] = o.Sharing
	}
	if !isNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableNamespaceNetworkPolicyRuleSpec struct {
	value *NamespaceNetworkPolicyRuleSpec
	isSet bool
}

func (v NullableNamespaceNetworkPolicyRuleSpec) Get() *NamespaceNetworkPolicyRuleSpec {
	return v.value
}

func (v *NullableNamespaceNetworkPolicyRuleSpec) Set(val *NamespaceNetworkPolicyRuleSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceNetworkPolicyRuleSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceNetworkPolicyRuleSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceNetworkPolicyRuleSpec(val *NamespaceNetworkPolicyRuleSpec) *NullableNamespaceNetworkPolicyRuleSpec {
	return &NullableNamespaceNetworkPolicyRuleSpec{value: val, isSet: true}
}

func (v NullableNamespaceNetworkPolicyRuleSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceNetworkPolicyRuleSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


