/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the CredentialsSpecMinio type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialsSpecMinio{}

// CredentialsSpecMinio Minio Credentials definition
type CredentialsSpecMinio struct {
	AccessId string `json:"accessId"`
	SecretKey string `json:"secretKey"`
}

// NewCredentialsSpecMinio instantiates a new CredentialsSpecMinio object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsSpecMinio(accessId string, secretKey string) *CredentialsSpecMinio {
	this := CredentialsSpecMinio{}
	this.AccessId = accessId
	this.SecretKey = secretKey
	return &this
}

// NewCredentialsSpecMinioWithDefaults instantiates a new CredentialsSpecMinio object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsSpecMinioWithDefaults() *CredentialsSpecMinio {
	this := CredentialsSpecMinio{}
	return &this
}

// GetAccessId returns the AccessId field value
func (o *CredentialsSpecMinio) GetAccessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessId
}

// GetAccessIdOk returns a tuple with the AccessId field value
// and a boolean to check if the value has been set.
func (o *CredentialsSpecMinio) GetAccessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessId, true
}

// SetAccessId sets field value
func (o *CredentialsSpecMinio) SetAccessId(v string) {
	o.AccessId = v
}

// GetSecretKey returns the SecretKey field value
func (o *CredentialsSpecMinio) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *CredentialsSpecMinio) GetSecretKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *CredentialsSpecMinio) SetSecretKey(v string) {
	o.SecretKey = v
}

func (o CredentialsSpecMinio) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialsSpecMinio) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessId"] = o.AccessId
	toSerialize["secretKey"] = o.SecretKey
	return toSerialize, nil
}

type NullableCredentialsSpecMinio struct {
	value *CredentialsSpecMinio
	isSet bool
}

func (v NullableCredentialsSpecMinio) Get() *CredentialsSpecMinio {
	return v.value
}

func (v *NullableCredentialsSpecMinio) Set(val *CredentialsSpecMinio) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsSpecMinio) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsSpecMinio) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsSpecMinio(val *CredentialsSpecMinio) *NullableCredentialsSpecMinio {
	return &NullableCredentialsSpecMinio{value: val, isSet: true}
}

func (v NullableCredentialsSpecMinio) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsSpecMinio) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


