/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the ProjectSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectSpec{}

// ProjectSpec project specification
type ProjectSpec struct {
	ClusterResourceQuota *ProjectResourceQuota `json:"clusterResourceQuota,omitempty"`
	// flag to indicate if this is the default project in the organization
	Default *bool `json:"default,omitempty"`
	DefaultClusterNamespaceQuota *ProjectResourceQuota `json:"defaultClusterNamespaceQuota,omitempty"`
}

// NewProjectSpec instantiates a new ProjectSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectSpec() *ProjectSpec {
	this := ProjectSpec{}
	return &this
}

// NewProjectSpecWithDefaults instantiates a new ProjectSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectSpecWithDefaults() *ProjectSpec {
	this := ProjectSpec{}
	return &this
}

// GetClusterResourceQuota returns the ClusterResourceQuota field value if set, zero value otherwise.
func (o *ProjectSpec) GetClusterResourceQuota() ProjectResourceQuota {
	if o == nil || isNil(o.ClusterResourceQuota) {
		var ret ProjectResourceQuota
		return ret
	}
	return *o.ClusterResourceQuota
}

// GetClusterResourceQuotaOk returns a tuple with the ClusterResourceQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSpec) GetClusterResourceQuotaOk() (*ProjectResourceQuota, bool) {
	if o == nil || isNil(o.ClusterResourceQuota) {
		return nil, false
	}
	return o.ClusterResourceQuota, true
}

// HasClusterResourceQuota returns a boolean if a field has been set.
func (o *ProjectSpec) HasClusterResourceQuota() bool {
	if o != nil && !isNil(o.ClusterResourceQuota) {
		return true
	}

	return false
}

// SetClusterResourceQuota gets a reference to the given ProjectResourceQuota and assigns it to the ClusterResourceQuota field.
func (o *ProjectSpec) SetClusterResourceQuota(v ProjectResourceQuota) {
	o.ClusterResourceQuota = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *ProjectSpec) GetDefault() bool {
	if o == nil || isNil(o.Default) {
		var ret bool
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSpec) GetDefaultOk() (*bool, bool) {
	if o == nil || isNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *ProjectSpec) HasDefault() bool {
	if o != nil && !isNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given bool and assigns it to the Default field.
func (o *ProjectSpec) SetDefault(v bool) {
	o.Default = &v
}

// GetDefaultClusterNamespaceQuota returns the DefaultClusterNamespaceQuota field value if set, zero value otherwise.
func (o *ProjectSpec) GetDefaultClusterNamespaceQuota() ProjectResourceQuota {
	if o == nil || isNil(o.DefaultClusterNamespaceQuota) {
		var ret ProjectResourceQuota
		return ret
	}
	return *o.DefaultClusterNamespaceQuota
}

// GetDefaultClusterNamespaceQuotaOk returns a tuple with the DefaultClusterNamespaceQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSpec) GetDefaultClusterNamespaceQuotaOk() (*ProjectResourceQuota, bool) {
	if o == nil || isNil(o.DefaultClusterNamespaceQuota) {
		return nil, false
	}
	return o.DefaultClusterNamespaceQuota, true
}

// HasDefaultClusterNamespaceQuota returns a boolean if a field has been set.
func (o *ProjectSpec) HasDefaultClusterNamespaceQuota() bool {
	if o != nil && !isNil(o.DefaultClusterNamespaceQuota) {
		return true
	}

	return false
}

// SetDefaultClusterNamespaceQuota gets a reference to the given ProjectResourceQuota and assigns it to the DefaultClusterNamespaceQuota field.
func (o *ProjectSpec) SetDefaultClusterNamespaceQuota(v ProjectResourceQuota) {
	o.DefaultClusterNamespaceQuota = &v
}

func (o ProjectSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ClusterResourceQuota) {
		toSerialize["clusterResourceQuota"] = o.ClusterResourceQuota
	}
	if !isNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if !isNil(o.DefaultClusterNamespaceQuota) {
		toSerialize["defaultClusterNamespaceQuota"] = o.DefaultClusterNamespaceQuota
	}
	return toSerialize, nil
}

type NullableProjectSpec struct {
	value *ProjectSpec
	isSet bool
}

func (v NullableProjectSpec) Get() *ProjectSpec {
	return v.value
}

func (v *NullableProjectSpec) Set(val *ProjectSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectSpec(val *ProjectSpec) *NullableProjectSpec {
	return &NullableProjectSpec{value: val, isSet: true}
}

func (v NullableProjectSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


