/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the SystemSyncConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemSyncConfig{}

// SystemSyncConfig system sync configuration
type SystemSyncConfig struct {
	// value to use as committer email when committing to destination git repository.
	CommitterEmail *string `json:"committerEmail,omitempty"`
	DestinationRepo *SystemSyncRepo `json:"destinationRepo,omitempty"`
	// resources to exclude from syncing
	ExcludedResources []SystemSyncResource `json:"excludedResources,omitempty"`
	// flag to indicate if git to system sync should be enabled
	GitToSystemSync *bool `json:"gitToSystemSync,omitempty"`
	// resources to include for syncing
	IncludedResources []SystemSyncResource `json:"includedResources,omitempty"`
	// flag to indicate if source repository should be used as destination repository
	SourceAsDestination *bool `json:"sourceAsDestination,omitempty"`
	SourceRepo *SystemSyncRepo `json:"sourceRepo,omitempty"`
	// flat to indicate if system to git sync should be enabled
	SystemToGitSync *bool `json:"systemToGitSync,omitempty"`
}

// NewSystemSyncConfig instantiates a new SystemSyncConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemSyncConfig() *SystemSyncConfig {
	this := SystemSyncConfig{}
	return &this
}

// NewSystemSyncConfigWithDefaults instantiates a new SystemSyncConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemSyncConfigWithDefaults() *SystemSyncConfig {
	this := SystemSyncConfig{}
	return &this
}

// GetCommitterEmail returns the CommitterEmail field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetCommitterEmail() string {
	if o == nil || isNil(o.CommitterEmail) {
		var ret string
		return ret
	}
	return *o.CommitterEmail
}

// GetCommitterEmailOk returns a tuple with the CommitterEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetCommitterEmailOk() (*string, bool) {
	if o == nil || isNil(o.CommitterEmail) {
		return nil, false
	}
	return o.CommitterEmail, true
}

// HasCommitterEmail returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasCommitterEmail() bool {
	if o != nil && !isNil(o.CommitterEmail) {
		return true
	}

	return false
}

// SetCommitterEmail gets a reference to the given string and assigns it to the CommitterEmail field.
func (o *SystemSyncConfig) SetCommitterEmail(v string) {
	o.CommitterEmail = &v
}

// GetDestinationRepo returns the DestinationRepo field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetDestinationRepo() SystemSyncRepo {
	if o == nil || isNil(o.DestinationRepo) {
		var ret SystemSyncRepo
		return ret
	}
	return *o.DestinationRepo
}

// GetDestinationRepoOk returns a tuple with the DestinationRepo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetDestinationRepoOk() (*SystemSyncRepo, bool) {
	if o == nil || isNil(o.DestinationRepo) {
		return nil, false
	}
	return o.DestinationRepo, true
}

// HasDestinationRepo returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasDestinationRepo() bool {
	if o != nil && !isNil(o.DestinationRepo) {
		return true
	}

	return false
}

// SetDestinationRepo gets a reference to the given SystemSyncRepo and assigns it to the DestinationRepo field.
func (o *SystemSyncConfig) SetDestinationRepo(v SystemSyncRepo) {
	o.DestinationRepo = &v
}

// GetExcludedResources returns the ExcludedResources field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetExcludedResources() []SystemSyncResource {
	if o == nil || isNil(o.ExcludedResources) {
		var ret []SystemSyncResource
		return ret
	}
	return o.ExcludedResources
}

// GetExcludedResourcesOk returns a tuple with the ExcludedResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetExcludedResourcesOk() ([]SystemSyncResource, bool) {
	if o == nil || isNil(o.ExcludedResources) {
		return nil, false
	}
	return o.ExcludedResources, true
}

// HasExcludedResources returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasExcludedResources() bool {
	if o != nil && !isNil(o.ExcludedResources) {
		return true
	}

	return false
}

// SetExcludedResources gets a reference to the given []SystemSyncResource and assigns it to the ExcludedResources field.
func (o *SystemSyncConfig) SetExcludedResources(v []SystemSyncResource) {
	o.ExcludedResources = v
}

// GetGitToSystemSync returns the GitToSystemSync field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetGitToSystemSync() bool {
	if o == nil || isNil(o.GitToSystemSync) {
		var ret bool
		return ret
	}
	return *o.GitToSystemSync
}

// GetGitToSystemSyncOk returns a tuple with the GitToSystemSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetGitToSystemSyncOk() (*bool, bool) {
	if o == nil || isNil(o.GitToSystemSync) {
		return nil, false
	}
	return o.GitToSystemSync, true
}

// HasGitToSystemSync returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasGitToSystemSync() bool {
	if o != nil && !isNil(o.GitToSystemSync) {
		return true
	}

	return false
}

// SetGitToSystemSync gets a reference to the given bool and assigns it to the GitToSystemSync field.
func (o *SystemSyncConfig) SetGitToSystemSync(v bool) {
	o.GitToSystemSync = &v
}

// GetIncludedResources returns the IncludedResources field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetIncludedResources() []SystemSyncResource {
	if o == nil || isNil(o.IncludedResources) {
		var ret []SystemSyncResource
		return ret
	}
	return o.IncludedResources
}

// GetIncludedResourcesOk returns a tuple with the IncludedResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetIncludedResourcesOk() ([]SystemSyncResource, bool) {
	if o == nil || isNil(o.IncludedResources) {
		return nil, false
	}
	return o.IncludedResources, true
}

// HasIncludedResources returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasIncludedResources() bool {
	if o != nil && !isNil(o.IncludedResources) {
		return true
	}

	return false
}

// SetIncludedResources gets a reference to the given []SystemSyncResource and assigns it to the IncludedResources field.
func (o *SystemSyncConfig) SetIncludedResources(v []SystemSyncResource) {
	o.IncludedResources = v
}

// GetSourceAsDestination returns the SourceAsDestination field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetSourceAsDestination() bool {
	if o == nil || isNil(o.SourceAsDestination) {
		var ret bool
		return ret
	}
	return *o.SourceAsDestination
}

// GetSourceAsDestinationOk returns a tuple with the SourceAsDestination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetSourceAsDestinationOk() (*bool, bool) {
	if o == nil || isNil(o.SourceAsDestination) {
		return nil, false
	}
	return o.SourceAsDestination, true
}

// HasSourceAsDestination returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasSourceAsDestination() bool {
	if o != nil && !isNil(o.SourceAsDestination) {
		return true
	}

	return false
}

// SetSourceAsDestination gets a reference to the given bool and assigns it to the SourceAsDestination field.
func (o *SystemSyncConfig) SetSourceAsDestination(v bool) {
	o.SourceAsDestination = &v
}

// GetSourceRepo returns the SourceRepo field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetSourceRepo() SystemSyncRepo {
	if o == nil || isNil(o.SourceRepo) {
		var ret SystemSyncRepo
		return ret
	}
	return *o.SourceRepo
}

// GetSourceRepoOk returns a tuple with the SourceRepo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetSourceRepoOk() (*SystemSyncRepo, bool) {
	if o == nil || isNil(o.SourceRepo) {
		return nil, false
	}
	return o.SourceRepo, true
}

// HasSourceRepo returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasSourceRepo() bool {
	if o != nil && !isNil(o.SourceRepo) {
		return true
	}

	return false
}

// SetSourceRepo gets a reference to the given SystemSyncRepo and assigns it to the SourceRepo field.
func (o *SystemSyncConfig) SetSourceRepo(v SystemSyncRepo) {
	o.SourceRepo = &v
}

// GetSystemToGitSync returns the SystemToGitSync field value if set, zero value otherwise.
func (o *SystemSyncConfig) GetSystemToGitSync() bool {
	if o == nil || isNil(o.SystemToGitSync) {
		var ret bool
		return ret
	}
	return *o.SystemToGitSync
}

// GetSystemToGitSyncOk returns a tuple with the SystemToGitSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemSyncConfig) GetSystemToGitSyncOk() (*bool, bool) {
	if o == nil || isNil(o.SystemToGitSync) {
		return nil, false
	}
	return o.SystemToGitSync, true
}

// HasSystemToGitSync returns a boolean if a field has been set.
func (o *SystemSyncConfig) HasSystemToGitSync() bool {
	if o != nil && !isNil(o.SystemToGitSync) {
		return true
	}

	return false
}

// SetSystemToGitSync gets a reference to the given bool and assigns it to the SystemToGitSync field.
func (o *SystemSyncConfig) SetSystemToGitSync(v bool) {
	o.SystemToGitSync = &v
}

func (o SystemSyncConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemSyncConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CommitterEmail) {
		toSerialize["committerEmail"] = o.CommitterEmail
	}
	if !isNil(o.DestinationRepo) {
		toSerialize["destinationRepo"] = o.DestinationRepo
	}
	if !isNil(o.ExcludedResources) {
		toSerialize["excludedResources"] = o.ExcludedResources
	}
	if !isNil(o.GitToSystemSync) {
		toSerialize["gitToSystemSync"] = o.GitToSystemSync
	}
	if !isNil(o.IncludedResources) {
		toSerialize["includedResources"] = o.IncludedResources
	}
	if !isNil(o.SourceAsDestination) {
		toSerialize["sourceAsDestination"] = o.SourceAsDestination
	}
	if !isNil(o.SourceRepo) {
		toSerialize["sourceRepo"] = o.SourceRepo
	}
	if !isNil(o.SystemToGitSync) {
		toSerialize["systemToGitSync"] = o.SystemToGitSync
	}
	return toSerialize, nil
}

type NullableSystemSyncConfig struct {
	value *SystemSyncConfig
	isSet bool
}

func (v NullableSystemSyncConfig) Get() *SystemSyncConfig {
	return v.value
}

func (v *NullableSystemSyncConfig) Set(val *SystemSyncConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemSyncConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemSyncConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemSyncConfig(val *SystemSyncConfig) *NullableSystemSyncConfig {
	return &NullableSystemSyncConfig{value: val, isSet: true}
}

func (v NullableSystemSyncConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemSyncConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


