/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the RepoUserPassCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepoUserPassCredentials{}

// RepoUserPassCredentials struct for RepoUserPassCredentials
type RepoUserPassCredentials struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// NewRepoUserPassCredentials instantiates a new RepoUserPassCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepoUserPassCredentials() *RepoUserPassCredentials {
	this := RepoUserPassCredentials{}
	return &this
}

// NewRepoUserPassCredentialsWithDefaults instantiates a new RepoUserPassCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepoUserPassCredentialsWithDefaults() *RepoUserPassCredentials {
	this := RepoUserPassCredentials{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *RepoUserPassCredentials) GetPassword() string {
	if o == nil || isNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepoUserPassCredentials) GetPasswordOk() (*string, bool) {
	if o == nil || isNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *RepoUserPassCredentials) HasPassword() bool {
	if o != nil && !isNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *RepoUserPassCredentials) SetPassword(v string) {
	o.Password = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *RepoUserPassCredentials) GetUsername() string {
	if o == nil || isNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepoUserPassCredentials) GetUsernameOk() (*string, bool) {
	if o == nil || isNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *RepoUserPassCredentials) HasUsername() bool {
	if o != nil && !isNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *RepoUserPassCredentials) SetUsername(v string) {
	o.Username = &v
}

func (o RepoUserPassCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepoUserPassCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !isNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableRepoUserPassCredentials struct {
	value *RepoUserPassCredentials
	isSet bool
}

func (v NullableRepoUserPassCredentials) Get() *RepoUserPassCredentials {
	return v.value
}

func (v *NullableRepoUserPassCredentials) Set(val *RepoUserPassCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableRepoUserPassCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableRepoUserPassCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepoUserPassCredentials(val *RepoUserPassCredentials) *NullableRepoUserPassCredentials {
	return &NullableRepoUserPassCredentials{value: val, isSet: true}
}

func (v NullableRepoUserPassCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepoUserPassCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


