/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the CredentialsSpecGcp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialsSpecGcp{}

// CredentialsSpecGcp GCP Credentials definition
type CredentialsSpecGcp struct {
	// Blob content of GCP Credentials Access JSON file
	File string `json:"file"`
}

// NewCredentialsSpecGcp instantiates a new CredentialsSpecGcp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsSpecGcp(file string) *CredentialsSpecGcp {
	this := CredentialsSpecGcp{}
	this.File = file
	return &this
}

// NewCredentialsSpecGcpWithDefaults instantiates a new CredentialsSpecGcp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsSpecGcpWithDefaults() *CredentialsSpecGcp {
	this := CredentialsSpecGcp{}
	return &this
}

// GetFile returns the File field value
func (o *CredentialsSpecGcp) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *CredentialsSpecGcp) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *CredentialsSpecGcp) SetFile(v string) {
	o.File = v
}

func (o CredentialsSpecGcp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialsSpecGcp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file"] = o.File
	return toSerialize, nil
}

type NullableCredentialsSpecGcp struct {
	value *CredentialsSpecGcp
	isSet bool
}

func (v NullableCredentialsSpecGcp) Get() *CredentialsSpecGcp {
	return v.value
}

func (v *NullableCredentialsSpecGcp) Set(val *CredentialsSpecGcp) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsSpecGcp) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsSpecGcp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsSpecGcp(val *CredentialsSpecGcp) *NullableCredentialsSpecGcp {
	return &NullableCredentialsSpecGcp{value: val, isSet: true}
}

func (v NullableCredentialsSpecGcp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsSpecGcp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


