/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the WorkloadTemplateList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkloadTemplateList{}

// WorkloadTemplateList Workload Template list
type WorkloadTemplateList struct {
	// API Version of the workload template list resource
	ApiVersion *string `json:"apiVersion,omitempty"`
	// List of the workload template resources
	Items []WorkloadTemplate `json:"items,omitempty"`
	// Kind of the workload template list resource
	Kind *string `json:"kind,omitempty"`
	Metadata *ListMetadata `json:"metadata,omitempty"`
}

// NewWorkloadTemplateList instantiates a new WorkloadTemplateList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkloadTemplateList() *WorkloadTemplateList {
	this := WorkloadTemplateList{}
	return &this
}

// NewWorkloadTemplateListWithDefaults instantiates a new WorkloadTemplateList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkloadTemplateListWithDefaults() *WorkloadTemplateList {
	this := WorkloadTemplateList{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *WorkloadTemplateList) GetApiVersion() string {
	if o == nil || isNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadTemplateList) GetApiVersionOk() (*string, bool) {
	if o == nil || isNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *WorkloadTemplateList) HasApiVersion() bool {
	if o != nil && !isNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *WorkloadTemplateList) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *WorkloadTemplateList) GetItems() []WorkloadTemplate {
	if o == nil || isNil(o.Items) {
		var ret []WorkloadTemplate
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadTemplateList) GetItemsOk() ([]WorkloadTemplate, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *WorkloadTemplateList) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []WorkloadTemplate and assigns it to the Items field.
func (o *WorkloadTemplateList) SetItems(v []WorkloadTemplate) {
	o.Items = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *WorkloadTemplateList) GetKind() string {
	if o == nil || isNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadTemplateList) GetKindOk() (*string, bool) {
	if o == nil || isNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *WorkloadTemplateList) HasKind() bool {
	if o != nil && !isNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *WorkloadTemplateList) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *WorkloadTemplateList) GetMetadata() ListMetadata {
	if o == nil || isNil(o.Metadata) {
		var ret ListMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadTemplateList) GetMetadataOk() (*ListMetadata, bool) {
	if o == nil || isNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *WorkloadTemplateList) HasMetadata() bool {
	if o != nil && !isNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ListMetadata and assigns it to the Metadata field.
func (o *WorkloadTemplateList) SetMetadata(v ListMetadata) {
	o.Metadata = &v
}

func (o WorkloadTemplateList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkloadTemplateList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: apiVersion is readOnly
	// skip: items is readOnly
	// skip: kind is readOnly
	if !isNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableWorkloadTemplateList struct {
	value *WorkloadTemplateList
	isSet bool
}

func (v NullableWorkloadTemplateList) Get() *WorkloadTemplateList {
	return v.value
}

func (v *NullableWorkloadTemplateList) Set(val *WorkloadTemplateList) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkloadTemplateList) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkloadTemplateList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkloadTemplateList(val *WorkloadTemplateList) *NullableWorkloadTemplateList {
	return &NullableWorkloadTemplateList{value: val, isSet: true}
}

func (v NullableWorkloadTemplateList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkloadTemplateList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


