/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the PulumiDestroyHooks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PulumiDestroyHooks{}

// PulumiDestroyHooks struct for PulumiDestroyHooks
type PulumiDestroyHooks struct {
	Destroy *LifecycleEventHooks `json:"destroy,omitempty"`
	Login *LifecycleEventHooks `json:"login,omitempty"`
	Preview *LifecycleEventHooks `json:"preview,omitempty"`
}

// NewPulumiDestroyHooks instantiates a new PulumiDestroyHooks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPulumiDestroyHooks() *PulumiDestroyHooks {
	this := PulumiDestroyHooks{}
	return &this
}

// NewPulumiDestroyHooksWithDefaults instantiates a new PulumiDestroyHooks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPulumiDestroyHooksWithDefaults() *PulumiDestroyHooks {
	this := PulumiDestroyHooks{}
	return &this
}

// GetDestroy returns the Destroy field value if set, zero value otherwise.
func (o *PulumiDestroyHooks) GetDestroy() LifecycleEventHooks {
	if o == nil || isNil(o.Destroy) {
		var ret LifecycleEventHooks
		return ret
	}
	return *o.Destroy
}

// GetDestroyOk returns a tuple with the Destroy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PulumiDestroyHooks) GetDestroyOk() (*LifecycleEventHooks, bool) {
	if o == nil || isNil(o.Destroy) {
		return nil, false
	}
	return o.Destroy, true
}

// HasDestroy returns a boolean if a field has been set.
func (o *PulumiDestroyHooks) HasDestroy() bool {
	if o != nil && !isNil(o.Destroy) {
		return true
	}

	return false
}

// SetDestroy gets a reference to the given LifecycleEventHooks and assigns it to the Destroy field.
func (o *PulumiDestroyHooks) SetDestroy(v LifecycleEventHooks) {
	o.Destroy = &v
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *PulumiDestroyHooks) GetLogin() LifecycleEventHooks {
	if o == nil || isNil(o.Login) {
		var ret LifecycleEventHooks
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PulumiDestroyHooks) GetLoginOk() (*LifecycleEventHooks, bool) {
	if o == nil || isNil(o.Login) {
		return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *PulumiDestroyHooks) HasLogin() bool {
	if o != nil && !isNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given LifecycleEventHooks and assigns it to the Login field.
func (o *PulumiDestroyHooks) SetLogin(v LifecycleEventHooks) {
	o.Login = &v
}

// GetPreview returns the Preview field value if set, zero value otherwise.
func (o *PulumiDestroyHooks) GetPreview() LifecycleEventHooks {
	if o == nil || isNil(o.Preview) {
		var ret LifecycleEventHooks
		return ret
	}
	return *o.Preview
}

// GetPreviewOk returns a tuple with the Preview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PulumiDestroyHooks) GetPreviewOk() (*LifecycleEventHooks, bool) {
	if o == nil || isNil(o.Preview) {
		return nil, false
	}
	return o.Preview, true
}

// HasPreview returns a boolean if a field has been set.
func (o *PulumiDestroyHooks) HasPreview() bool {
	if o != nil && !isNil(o.Preview) {
		return true
	}

	return false
}

// SetPreview gets a reference to the given LifecycleEventHooks and assigns it to the Preview field.
func (o *PulumiDestroyHooks) SetPreview(v LifecycleEventHooks) {
	o.Preview = &v
}

func (o PulumiDestroyHooks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PulumiDestroyHooks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Destroy) {
		toSerialize["destroy"] = o.Destroy
	}
	if !isNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	if !isNil(o.Preview) {
		toSerialize["preview"] = o.Preview
	}
	return toSerialize, nil
}

type NullablePulumiDestroyHooks struct {
	value *PulumiDestroyHooks
	isSet bool
}

func (v NullablePulumiDestroyHooks) Get() *PulumiDestroyHooks {
	return v.value
}

func (v *NullablePulumiDestroyHooks) Set(val *PulumiDestroyHooks) {
	v.value = val
	v.isSet = true
}

func (v NullablePulumiDestroyHooks) IsSet() bool {
	return v.isSet
}

func (v *NullablePulumiDestroyHooks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePulumiDestroyHooks(val *PulumiDestroyHooks) *NullablePulumiDestroyHooks {
	return &NullablePulumiDestroyHooks{value: val, isSet: true}
}

func (v NullablePulumiDestroyHooks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePulumiDestroyHooks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


