/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the ResourceTemplateProviderHooks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceTemplateProviderHooks{}

// ResourceTemplateProviderHooks struct for ResourceTemplateProviderHooks
type ResourceTemplateProviderHooks struct {
	Pulumi *PulumiProviderHooks `json:"pulumi,omitempty"`
	Terraform *TerraformProviderHooks `json:"terraform,omitempty"`
}

// NewResourceTemplateProviderHooks instantiates a new ResourceTemplateProviderHooks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceTemplateProviderHooks() *ResourceTemplateProviderHooks {
	this := ResourceTemplateProviderHooks{}
	return &this
}

// NewResourceTemplateProviderHooksWithDefaults instantiates a new ResourceTemplateProviderHooks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceTemplateProviderHooksWithDefaults() *ResourceTemplateProviderHooks {
	this := ResourceTemplateProviderHooks{}
	return &this
}

// GetPulumi returns the Pulumi field value if set, zero value otherwise.
func (o *ResourceTemplateProviderHooks) GetPulumi() PulumiProviderHooks {
	if o == nil || isNil(o.Pulumi) {
		var ret PulumiProviderHooks
		return ret
	}
	return *o.Pulumi
}

// GetPulumiOk returns a tuple with the Pulumi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTemplateProviderHooks) GetPulumiOk() (*PulumiProviderHooks, bool) {
	if o == nil || isNil(o.Pulumi) {
		return nil, false
	}
	return o.Pulumi, true
}

// HasPulumi returns a boolean if a field has been set.
func (o *ResourceTemplateProviderHooks) HasPulumi() bool {
	if o != nil && !isNil(o.Pulumi) {
		return true
	}

	return false
}

// SetPulumi gets a reference to the given PulumiProviderHooks and assigns it to the Pulumi field.
func (o *ResourceTemplateProviderHooks) SetPulumi(v PulumiProviderHooks) {
	o.Pulumi = &v
}

// GetTerraform returns the Terraform field value if set, zero value otherwise.
func (o *ResourceTemplateProviderHooks) GetTerraform() TerraformProviderHooks {
	if o == nil || isNil(o.Terraform) {
		var ret TerraformProviderHooks
		return ret
	}
	return *o.Terraform
}

// GetTerraformOk returns a tuple with the Terraform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTemplateProviderHooks) GetTerraformOk() (*TerraformProviderHooks, bool) {
	if o == nil || isNil(o.Terraform) {
		return nil, false
	}
	return o.Terraform, true
}

// HasTerraform returns a boolean if a field has been set.
func (o *ResourceTemplateProviderHooks) HasTerraform() bool {
	if o != nil && !isNil(o.Terraform) {
		return true
	}

	return false
}

// SetTerraform gets a reference to the given TerraformProviderHooks and assigns it to the Terraform field.
func (o *ResourceTemplateProviderHooks) SetTerraform(v TerraformProviderHooks) {
	o.Terraform = &v
}

func (o ResourceTemplateProviderHooks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceTemplateProviderHooks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Pulumi) {
		toSerialize["pulumi"] = o.Pulumi
	}
	if !isNil(o.Terraform) {
		toSerialize["terraform"] = o.Terraform
	}
	return toSerialize, nil
}

type NullableResourceTemplateProviderHooks struct {
	value *ResourceTemplateProviderHooks
	isSet bool
}

func (v NullableResourceTemplateProviderHooks) Get() *ResourceTemplateProviderHooks {
	return v.value
}

func (v *NullableResourceTemplateProviderHooks) Set(val *ResourceTemplateProviderHooks) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceTemplateProviderHooks) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceTemplateProviderHooks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceTemplateProviderHooks(val *ResourceTemplateProviderHooks) *NullableResourceTemplateProviderHooks {
	return &NullableResourceTemplateProviderHooks{value: val, isSet: true}
}

func (v NullableResourceTemplateProviderHooks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceTemplateProviderHooks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


