/*
Kubernetes Operations APIs

Kubernetes Operations APIs

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rafaysdkgov3

import (
	"encoding/json"
)

// checks if the ResourceTemplateList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceTemplateList{}

// ResourceTemplateList List of resource templates
type ResourceTemplateList struct {
	// API Version of the resource templates list
	ApiVersion *string `json:"apiVersion,omitempty"`
	// List of the resource templates
	Items []ResourceTemplate `json:"items,omitempty"`
	// Kind of the resource template list
	Kind *string `json:"kind,omitempty"`
	Metadata *ListMetadata `json:"metadata,omitempty"`
}

// NewResourceTemplateList instantiates a new ResourceTemplateList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceTemplateList() *ResourceTemplateList {
	this := ResourceTemplateList{}
	return &this
}

// NewResourceTemplateListWithDefaults instantiates a new ResourceTemplateList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceTemplateListWithDefaults() *ResourceTemplateList {
	this := ResourceTemplateList{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *ResourceTemplateList) GetApiVersion() string {
	if o == nil || isNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTemplateList) GetApiVersionOk() (*string, bool) {
	if o == nil || isNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *ResourceTemplateList) HasApiVersion() bool {
	if o != nil && !isNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *ResourceTemplateList) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ResourceTemplateList) GetItems() []ResourceTemplate {
	if o == nil || isNil(o.Items) {
		var ret []ResourceTemplate
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTemplateList) GetItemsOk() ([]ResourceTemplate, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ResourceTemplateList) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ResourceTemplate and assigns it to the Items field.
func (o *ResourceTemplateList) SetItems(v []ResourceTemplate) {
	o.Items = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ResourceTemplateList) GetKind() string {
	if o == nil || isNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTemplateList) GetKindOk() (*string, bool) {
	if o == nil || isNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ResourceTemplateList) HasKind() bool {
	if o != nil && !isNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ResourceTemplateList) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ResourceTemplateList) GetMetadata() ListMetadata {
	if o == nil || isNil(o.Metadata) {
		var ret ListMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTemplateList) GetMetadataOk() (*ListMetadata, bool) {
	if o == nil || isNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ResourceTemplateList) HasMetadata() bool {
	if o != nil && !isNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ListMetadata and assigns it to the Metadata field.
func (o *ResourceTemplateList) SetMetadata(v ListMetadata) {
	o.Metadata = &v
}

func (o ResourceTemplateList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceTemplateList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: apiVersion is readOnly
	// skip: items is readOnly
	// skip: kind is readOnly
	if !isNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableResourceTemplateList struct {
	value *ResourceTemplateList
	isSet bool
}

func (v NullableResourceTemplateList) Get() *ResourceTemplateList {
	return v.value
}

func (v *NullableResourceTemplateList) Set(val *ResourceTemplateList) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceTemplateList) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceTemplateList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceTemplateList(val *ResourceTemplateList) *NullableResourceTemplateList {
	return &NullableResourceTemplateList{value: val, isSet: true}
}

func (v NullableResourceTemplateList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceTemplateList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


